### ISSUE TITLE
Upload from eclipse

### ISSUE THREAD

**Issue by hayama600** [c4ev3/EV3-API#14]
I have question about compiled file.
When i compile file on ev3 exists .elf file, but ev3 can't start that file and I see that file only when connect ev3 with computer.
Does anyone know how to solve this problem?

**Comment by a3f** [comment]
The eclipse plugin should upload a *.rbf file as well. This rbf file is what's displayed by the LEGO menu. Under the hood it just executed the .elf file.

**Comment by hayama600** [comment]
Yes, eclipse generates two files .rbf and .elf. 
But I can't find them on ev4..
When creating project I've selected Upload path: Internal Brick storage instead of SD card.
Can that be a problem ?

**Comment by hayama600** [comment]
At monday i can buy sd card  :)
I've tried with usb stick formated in fat32 but that didn't work.
Is there a way to use usb stick instead of sd card?

**Comment by a3f** [comment]
The project creation wizard has a USB option, but I don't think I ever used it. Sorry, no idea.

**Comment by hayama600** [comment]
I've tried but it didn't work. 
I will buy sd card.
Thanks for your help!

**Comment by hayama600** [comment]
Hello, i've tried with sd card and now i can see Hello world program on ev3 but now I have new problem.
When I click on ev3 my program I see only program name for few seconds but program is never started.
Do you have idea what went wrong?

**Comment by hayama600** [comment]
Thanks for your answer, I will try with linux.

**Comment by JakubVanek** [comment]
Hi,

I've tried to build a musl toolchain for EV3 using crosstool-ng some time ago, but I had some problems with uploading the generated ELFs. I don't know if the binaries work either.

[c4ev3-static.txt](https://github.com/c4ev3/EV3-API/files/2017770/c4ev3-static.txt)
[c4ev3-dynamic.txt](https://github.com/c4ev3/EV3-API/files/2017771/c4ev3-dynamic.txt)

A manually-built toolchain using glibc is probably going to be better, though.

Regards,

Jakub Vaněk

**Comment by a3f** [comment]
I've built [x86-{macOS, Linux, Windows} → EV3 Toolchains](https://github.com/c4ev3/toolchain/releases), but they are in need of testing.
They include the most recent GCC (8.1.0 with Binutils 2.30) and target Linux 2.6.33-rc4 with glibc 2.8 (Firmware 1.09D).

A user in the Gitter channel was kind enough to verify the macOS one works, but it would be nice if the others can be tested as well. If you have issue using them, please open bug reports at https://github.com/c4ev3/toolchain/issues. I am closing this issue.

@JakubVanek I tried crosstool-ng as well, but the recent version doesn't support Linux v2.6.*, so I did the build steps manually. Thanks for the configs though, might be useful to others.

>  had some problems with uploading the generated ELFs

ev3duder issues? If so, could you open a bug report over there?
