### ISSUE TITLE
Problems to add support for Hitechnic Color Sensor V2

### ISSUE THREAD

**Issue by Lemru** [c4ev3/EV3-API#15]
I'm trying to get a Hitechnic Color Sensor V2 to work, but only the color number mode is working so far.

Here is, what I've done:

In file `ev3sensor.h` following lines were added:

    //HiTechnc Color V2
    #define HT_COL2_COL 30  // Color
    #define HT_COL2_RED 31  // Red
    #define HT_COL2_GRN 32  // Green
    #define HT_COL2_BLU 33  // Blue
    #define HT_COL2_WHT 34  // White
    #define HT_COL2_RAW 35  // RGBW - Raw
    #define HT_COL2_NRM 36  // RGBW - Normalized
    #define HT_COL2_ALL 37  // CRGBW

In file `ev3sensor.c` the lines in section sensor setup were added. The values were taken from Lego's firmware (version 1.09) documentation:

    //HiTechnc Color V2
    #define HTC_TYPE 54
    #define HTC_MODE_COL 0      // Color
    #define HTC_MODE_RED 1      // Red
    #define HTC_MODE_GRN 2      // Green
    #define HTC_MODE_BLU 3      // Blue
    #define HTC_MODE_WHT 4      // White
    #define HTC_MODE_RAW 5      // RGBW - Raw
    #define HTC_MODE_NRM 6      // RGBW - Normalized
    #define HTC_MODE_ALL 7      // CRGBW

In function `ReadSensorData` the switch statement has been extended by following cases:

    case HT_COL2_COL:
    	return readIicSensor(sensorPort);
    case HT_COL2_RED:
    	return readIicSensor(sensorPort);
    case HT_COL2_GRN:
    	return readIicSensor(sensorPort);
    case HT_COL2_BLU:
    	return readIicSensor(sensorPort);
    case HT_COL2_WHT:
    	return readIicSensor(sensorPort);
    case HT_COL2_RAW:
    	return readIicSensor(sensorPort);
    case HT_COL2_NRM:
    	return readIicSensor(sensorPort);
    case HT_COL2_ALL:
    	return readIicSensor(sensorPort);

and in function `ReadSensor:`

    case HT_COL2_COL:
    	return *((DATA8*)data);
    case HT_COL2_RED:
    	return *((DATA8*)data);
    case HT_COL2_GRN:
    	return *((DATA8*)data);
    case HT_COL2_BLU:
    	return *((DATA8*)data);
    case HT_COL2_WHT:
    	return *((DATA8*)data);

(the missing cases will be handled by function `ReadSensorData)`

I successfully compiled the API with the included make file and wrote a simple test program like follows:

    #include <ev3.h>
    #include <basictypes.h>
    
    int main(void)
    {
    	int i;
    	char str[32];
    
    	InitEV3();
    	setSensorMode(IN_3, HT_COL2_GRN);
    	Wait(MS_500);
    
    	for (i=0; i<10; i++)
    	{
    		LcdClearDisplay();
    		LcdSelectFont(2);
    		sprintf (str, "%i", ((DATA8*)readSensorData(IN_3))[0]);
    		LcdText(1, 50, 50, str);
    		Wait(MS_500);
    	}
    
    	FreeEV3();
    	return 0;
    }

Whatever mode I used in function `setSensorMode` - I always got a color number. Then I changed the sensor mode with Lego's EV3-G software. Now I got a four byte result, which presumably has been the values for RGB + White.
But:
These values never changed. Whenever I started the program, the same values were delivered. Obviously the sensor wasn't polling for new values.

What am I missing? It seems that function `setSensorMode` doesn't work at all for IIC sensor types. I'm wondering, if it works for the NXT_TEMP type, which is also an IIC sensor and has two modes. I don't have such, but was this ever tested?

Any help to fix this problem is welcome!

Many thanks in advance,

Rainer

**Comment by Lemru** [comment]
Thanks for your support!

In this example I skipped the inner loop, which wrote up to five indices to the display.

Do you have access to a Lego temperature sensor to check, if you can change the mode for this device? In Lego's firmware by default mode 0 is selected, which explains, why I get at least a color number. I would like to check, if the temperature sensor always provides its values in Celsius or if also Fahrenheit values are delivered.

**Comment by a3f** [comment]
> Do you have access to a Lego temperature sensor to check

I've no EV3 available, sorry. You might want to ask in the [Gitter channel](https://gitter.im/c4ev3/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge). I can't assist further with this...

**Comment by Lemru** [comment]
ok - thanks for the hint. I will do some further investigations within Lego's firmware. It seems that the documentation is outdated. So I'll try to get the obvious differences sorted out first.

**Comment by a3f** [comment]
I would leave the issue open, maybe someone else can chime in.

**Comment by maximmasterr** [comment]
Need to add iic transaction 
See microsoft/pxt-ev3 libs/core/input.ts

**Comment by simonedegiacomi** [comment]
Hi, I added the support for iic transactions, copying the implementation from microsoft/pxt-ev3 libs/core/input.ts and I'm also working on the HT color sensor.
I made a pull request that contains the new iic code without the color sensor support (it isn't ready yet), but in the meantime you can try [here](https://github.com/simonedegiacomi/EV3-API/blob/ht-color-sensor/src/ev3_sensors/ht_color.c) my implementation.

**Comment by simonedegiacomi** [comment]
The sensor implementation is now merged https://github.com/c4ev3/EV3-API/pull/48
