### ISSUE TITLE
LcdClean() seems to skip the rest of the EV3 program that is run

### ISSUE THREAD

**Issue by Electrenator** [c4ev3/EV3-API#26]
When printing on the lcd with LcdPrintf() and then clearing it with LcdClean() seems to always skip the rest of the program that still needs to be run on the EV3.

**Comment by dnlmlr** [comment]
Could you clarify what you mean by "skip the rest of the program"? Does the program exit after reaching `LcdClean` or do you mean something else?

**Comment by Electrenator** [comment]
The program exits when reaching the `LcdClean` function.

**Comment by dnlmlr** [comment]
That is of course not supposed to happen. If this is an issue with the API code, it seems realy strange though that this never occoured before. Do the other LCD related functions (`Ev3Printf` or the older `LcdPrintf`) work? Would you mind providing code for a minimal functional program that produces the error for you? That might help understanding what goes wrong and/or allow to maybe replicate the problem.

**Comment by Electrenator** [comment]
Have never tried to use `Ev3Printf`, it wasn't in the `commands.pdf` and can't test it at the moment but I've used this code to get the result that I had described;
```c
#include <ev3.h>

int main(void){
	int x, y;

	for(x = 0; x < 10; x++){
		for(y = 0; y < 8; y++){
			if(x % 2 == 0)
			{
				LcdPrintf(1, "Hello World!\n");
				LcdPrintf(0, "Hello World!\n");
			}else{
				LcdPrintf(0, "Hello World!\n");
				LcdPrintf(1, "Hello World!\n");
			}
		}
		Wait(MS_500);
	}
}
```

**Comment by Electrenator** [comment]
Yes, `Ev3Printf` and `LcdPrintf` work with the above code

**Comment by a3f** [comment]
Did you figure out why LcdClean behaved strangely for you? Can this issue be closed?

**Comment by Electrenator** [comment]
No, I didn't figure it out in the end. Could have been something with the device itself because it did work with other EV3s that I could test it on.

**Comment by a3f** [comment]
Possibly different firmware versions? Could you check?
