### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by JakubVanek** [c4ev3/EV3-API#3]
Hi everyone,
I'd like to know which licenses can I use for a project which makes use of this project by compiling user programs with it. Particularly, I'd like to know if I can use GPL 3.0 for the engine.
I'm confused by that this project is `released under the terms of the Mozilla Public License Version 1.1 and GNU General Public License for the Sensors-API.`
Is it even legal to distribute a program which makes use of both parts (i.e. linking code covered by two incompatible licenses together)?

**Comment by a3f** [comment]
Part of the the sensor headers are taken from the official LEGO Mindstorms source code which is GPL'd. 

If you compile both MPL'd and GPL'd code into your library, you will have to make the source code as a whole available under the GPL.

HTH.
