### ISSUE TITLE
bluetooth messaging

### ISSUE THREAD

**Issue by mzajkaniha** [c4ev3/EV3-API#31]
does c4ev3 support bluetooth messaging betwen two ev3 bricks?

**Comment by mzajkaniha** [comment]
?

**Comment by a3f** [comment]
There is pull request #22 that adds support for this. I am still in process of reviewing it.

You can try it out by forking the original repository: https://github.com/simonedegiacomi/EV3-API/tree/develop

**Comment by a3f** [comment]
With #42 merged, there is now support for this in the library. Check it out!
