### ISSUE TITLE
Relicensing the EV3-API as GPL-2.0-or-later

### ISSUE THREAD

**Issue by a3f** [c4ev3/EV3-API#34]
*Update:* It has since turned out, the MPL1.1 licensed parts are infringing on GPL-2.0 parts of the original LEGO Firmware, thus the only compatible license choice we have
is GPL-3.0-or-later as that's the one used for the sensor code. It would be nice if we could've GPL-2.0-or-later however.

Permission of following authors needed to relicense as GPL-2.0-or-later

- [x] Carsten Zeiffert (@carstenz)
- [x] Simón Rodriguez Perez (@simonRP)
- [x] Daniel Müller (@dnlmlr)
- [x] Alexander Rose (through @dnlmlr)
- [x] Ahmad Fatoum (@a3f)
- [x] LEGO Group (as their code was GPL-2.0-or-later to begin with)

---

### Current Situation

Since mid 2016, we have been redistributing binary packages of the EV3-API along with the c4ev3 toolchain, which have been downloaded nearly 10.000 times and, according to feedback, found quite some users in introductory programming courses around the world.

It has come to my attention, however, that this redistribution was a license violation: The Mozilla Public License (MPL) 1.1 used for parts of the API originally created by John Hansen is incompatible with the GNU General Public License (GPL) 3.0 used for the sensors API and likely some of the other files that were written after exposure to the lms2012 GPL-2.0-or-later licensed headers.

### Binary download take down

To respect the authors original copyright, I've since taken down our binary downloads. I am not a lawyer, but my interpretation is that users may still use the self-built library, 
but they are also not legally allowed to redistribute their results.

### Relicensing

I'd like to ask the copyright holders on the MPL-1.1 licensed code to relicense their code as  MPL-2.0. The MPL-2.0 is explicitly compatible with the GPL-2.0 and the GPL-3.0, so we could continue to provide binary downloads and integrate code from other GPL-licensed projects.

Contributors to MPL-1.1 code and whose permission is required:

- [ ] Simón Rodriguez Perez (@simonRP)
- [x] Ahmad Fatoum (@a3f)
- [x] Daniel Müller (@dnlmlr)
- [x] Joshua 'Pip' Minter (@matanui159)
- [ ] John Hansen (couldn't find a Github handle, but contacted him via LinkedIn)

# Questions

* Why not relicense the GPL parts? The lms2012 software used in the LEGO firmware is itself licensed under the GPL-2.0-or-later, so it makes most sense to have a license that's compatible to it.

* What happens if not all copyright holders agree to relicense all their current contributions to the EV3-API under the new license? As I don't actively develop this (and never really did, I did mostly the Toolchain/Uploader part), it's unlikely that we'll reimplement the missing functionality.  In this case, binary downloads will not be reinstated to respect the original authors' copyright.

* Is there another way? I don't see any. I am not a lawyer and open to discussion.

Thanks for reading.

**Comment by a3f** [comment]
I, Ahmad Fatoum, give permission to license my contributions to the EV3-API under the MPL-2.0 or later.

**Comment by matanui159** [comment]
Completely forgot I made a 2 character change on this project.

I, Joshua Minter, give permission to license my contributions to the EV3-API under the Mozilla Public License 1.1 or any later version published by the Mozilla Foundation.

Wish y'all luck, I find MPL to be a very nice and underappreciated license.

**Comment by Davester47** [comment]
I noticed that some of the MPL licensed code directly copies from the LEGO sources that are GPL 2. Line 231 - 251 of ev3_output.c is a **DIRECT** from c_output.c in the LEGO sources distribution. Just thought I should let you know, this is technically a GPL violation.

**Comment by a3f** [comment]
> I noticed that some of the MPL licensed code directly copies from the LEGO sources that are GPL 2. Line 231 - 251 of ev3_output.c is a **DIRECT COPY** from c_output.c in the LEGO sources distribution. Just thought I should let you know, this is technically a GPL violation, and it isn't going to be legal. I don't think making it MPL v2 is going to cut it.

Thanks, I wasn't aware of this. I've now deleted the commented out code snippets. IANAL, but my understanding is that had these snippets been in a separate file with proper attribution, copyright notice and license information, it would've been ok as they aren't used as code and only serve the purpose of interoperability. If you have a different take or know of any other such snippets, please let me know.

**Comment by Davester47** [comment]
I believe the problem runs much deeper. I'm sorry, but your EV3-API **very** closely resembles lego source code that is covered by the GPL.
Here's an example from ev3_output.c:
```C
bool OutputInit(void)
{
  if (OutputInitialized())
	return true;

  MOTORDATA * pTmp;

  // To ensure that pMotor is never uninitialised
  OutputInstance.pMotor = OutputInstance.MotorData;

  // Open the handle for writing commands
  OutputInstance.PwmFile = open(LMS_PWM_DEVICE_NAME, O_RDWR);

  if (OutputInstance.PwmFile >= 0)
  {
	// Open the handle for reading motor values - shared memory
	OutputInstance.MotorFile = open(LMS_MOTOR_DEVICE_NAME, O_RDWR | O_SYNC);
	if (OutputInstance.MotorFile >= 0)
	{
	  pTmp = (MOTORDATA*)mmap(0, sizeof(OutputInstance.MotorData), PROT_READ | PROT_WRITE, MAP_FILE | MAP_SHARED, OutputInstance.MotorFile, 0);
	  if (pTmp == MAP_FAILED)
	  {
//        LogErrorNumber(OUTPUT_SHARED_MEMORY);
		close(OutputInstance.MotorFile);
		close(OutputInstance.PwmFile);
		OutputInstance.MotorFile = -1;
		OutputInstance.PwmFile = -1;
	  }
	  else
	  {
		OutputInstance.pMotor = pTmp;
		return OutputOpen();
	  }
	}
  }
  return false;
}
```
And here is that same function in c_output.c of mindboards/ev3sources, which is part of the Lego code:
```C
RESULT    cOutputInit(void)
{
  RESULT      Result = FAIL;
  MOTORDATA   *pTmp;

  // To ensure that pMotor is never uninitialised
  OutputInstance.pMotor  =  OutputInstance.MotorData;

  // Open the handle for writing commands
  OutputInstance.PwmFile  =  open(PWM_DEVICE_NAME,O_RDWR);

  if (OutputInstance.PwmFile >= 0)
  {

    // Open the handle for reading motor values - shared memory
    OutputInstance.MotorFile  =  open(MOTOR_DEVICE_NAME,O_RDWR | O_SYNC);
    if (OutputInstance.MotorFile >= 0)
    {
      pTmp  =  (MOTORDATA*)mmap(0, sizeof(OutputInstance.MotorData), PROT_READ | PROT_WRITE, MAP_FILE | MAP_SHARED, OutputInstance.MotorFile, 0);

      if (pTmp == MAP_FAILED)
      {
        LogErrorNumber(OUTPUT_SHARED_MEMORY);
        close(OutputInstance.MotorFile);
        close(OutputInstance.PwmFile);
      }
      else
      {
        OutputInstance.pMotor  =  (MOTORDATA*)pTmp;
        Result  =  cOutputOpen();
      }
    }
  }
```
These two functions are scary similar, and the comments are exactly the same. You will find that this function is not unique as you compare the code.  Now, I'm no lawyer, but you may be able to release EV3-API under version 2 or later of the GPL and do away with the MPL. I don't think the original authors need to be consulted, since it doesn't look like they did much code writing. This might be a bigger problem then you realize.

**Comment by JakubVanek** [comment]
ev3_display is tainted as well:
https://github.com/c4ev3/EV3-API/blob/master/API/ev3_lcd.c
https://github.com/mindboards/ev3sources/blob/master/lms2012/c_ui/source/d_lcd.c
`dLcdDrawPixel` is exactly the same between the two versions. Other functions also look very similar.

**Comment by JakubVanek** [comment]
I, Jakub Vaněk, give permission to license all my current and future contributions to the EV3-API under a) the Mozilla Public License 1.1 or any later version published by the Mozilla Foundation, or b) the GNU General Public License 2.0 or any later version published by the Free Software Foundation.

It seems that Mozilla itself in the MPL-1.1 days had used a MPL/GPL/LGPL trilicense, but this changed with MPL-2.0.

**Comment by a3f** [comment]
@Davester47 
I don't have a complete history of the project, but yes, if even the very first version had GPL code in it, we could just relicense as GPL. To verify, I'd need the original code, which apparently was only available as a [lms_api.zip](http://bricxcc.sourceforge.net/test_releases/lms_api.zip) on the bricxcc website, but is now unavailable. Does someone still have a copy?

@JakubVanek Thanks for spotting. I will compare these when I get a hold of the original code.

> It seems that Mozilla itself in the MPL-1.1 days had used a MPL/GPL/LGPL trilicense, but this changed with MPL-2.0.

Ye, but the code we have only indicates MPL-1.1 compatibility. Thanks for the relicensing on your PRs. I'll try to go through them this weekend.

**Comment by a3f** [comment]
Ok, found it: https://web.archive.org/web/20171012010347/http://bricxcc.sourceforge.net/test_releases/lms_api.zip

`dLcdDrawPixel` and `OutputInit` are indeed in there since the very first version.

**Comment by a3f** [comment]
The LEGO code used in the original lms_api was GPL-2.0-or-later licensed. Derivative works of it must be distributed under the same terms. We have GPL-3.0-or-later licensed files in the repository as well, so the logical thing to do would be adopting GPL-3.0-or-later as license going forward. Having GPL-2.0-or-later instead could be nice, so we can reuse GPL-2.0-only code as well, but not strictly necessary. The GPL-3.0's anti-Tivoization clause doesn't affect end users much, because they can just suggest use of [ev3duder](https://github.com/c4ev3/ev3duder).

Authors of the GPL-3.0-or-later code (sensors):

- [ ] Carsten Zeiffert
- [ ]  Simón Rodriguez Perez (@simonRP)
- [ ] Daniel Müller (@dnlmlr)
- [ ] Alexander Rose (through @dnlmlr)
- [x] Ahmad Fatoum (@a3f)
- [x] LEGO Group

If all agree to relicense under the GPL-2.0-or-later, we can adopt this as license. Till then I'll take the necessary steps for GPL-3.0-or-later compliance. Any comments?

**Comment by dnlmlr** [comment]
I want to mention that all my contributions to this code were all made as an employee of the Aschaffenburg University of Applied Sciences. I don't know about the legal implications of this. 
As far as it is in my rights to do so:

I, Daniel Müller, give permission to license all my current and future contributions to the EV3-API under a) the Mozilla Public License 1.1 or any later version published by the Mozilla Foundation, or b) the GNU General Public License 2.0 or any later version published by the Free Software Foundation.

**Comment by a3f** [comment]
@dnlmlr AFAIR, my contract didn't relinquish my rights to the code, but only gave the h-ab the right to use it. I'd assume for you it's the same, but you can check. Thanks for the assignment. Alexander Rose's permission would be required as well. Do you have means to contact him?

**Comment by dnlmlr** [comment]
I just looked up the @th-ab.de email address  that I used to contact him the last time. I will send you the address via email, since I don't want to make the address public here with his consent.

**Comment by a3f** [comment]
Ah, the address is in the git logs anyway. I'll shoot him a mail. Thanks

**Comment by carstenz** [comment]
Hi,

That's fine with me, I'll update the license to GPL-2.0-or-later in my
repository, later today. I see that I added the GPL-3.0-or-later license
text to files derived from lms_api, which was a mistake on my part.

- Carsten

**Comment by a3f** [comment]
All copyright holders to the GPL-3.0+ code have agreed with a GPL-2.0+ relicensing. I've amended our license statements. Thanks everyone for your input!
