### ISSUE TITLE
SIGALRM syscall interruptions

### ISSUE THREAD

**Issue by JakubVanek** [c4ev3/EV3-API#36]
Hi,

I'm thinking about how to solve the problem with timers interrupting running syscalls.
* Implement syscall restarting: https://github.com/openjdk/jdk11u/blob/d46b56eb81b07b452141c7dcd078d33fc8e49d63/src/hotspot/os/linux/os_linux.inline.hpp#L84
  - :heavy_plus_sign: Minimal changes to the code surrounding the syscall.
  - :heavy_minus_sign: Has to be followed in user code as well.
* Make SIGALRM restart the syscalls automatically: [`SA_RESTART`](https://www.gnu.org/software/libc/manual/html_node/Flags-for-Sigaction.html)
  - :heavy_plus_sign: Small change just in the related code.
  - :heavy_minus_sign: Not all syscalls are restartable (https://stackoverflow.com/a/48553220).
  - added in 7a65ecaa1df0094e4effa99220edf5edde5382fe
* Provide an alternative implementation based on threads
  - :heavy_plus_sign: Removes (most?) interruptions due to signals, so changes to syscall code are not necessary.
  - :heavy_minus_sign: Callbacks need to be aware that they're executing in a different thread context (locking/atomic is necessary).
  - :heavy_minus_sign: Memory overhead of threads (however I have no data to determine the actual impact).
  - :heavy_minus_sign: Scheduling/CPU overhead of threads (ditto).

Best regards,

Jakub

**Comment by a3f** [comment]
`SA_RESTART` is a good default, I think.
