### ISSUE TITLE
LcdClean() doesn't reset cursor position

### ISSUE THREAD

**Issue by Davester47** [c4ev3/EV3-API#39]
I ran into the problem mentioned in #13 concerning LcdClean() where it doesn't reset the cursor position. I've created a program to demonstrate the problem:
```C
#include <ev3.h>

int main() {
  InitEV3();

  LcdPrintf(1, "Hello World!\n");
  Wait(1000);
  LcdClean();
  LcdPrintf(1, "I am a line farther down than I should be.\n");
  Wait(2000);

  FreeEV3();
  return 0;
}
```
I realize that this might break code for a small subset of users, but it would be an easy enough fix as long as they find out about it.

**Comment by a3f** [comment]
As mentioned in the just-merged pull request, there's `Ev3Clear()` for this. Closing.
