### ISSUE TITLE
NXT ultrasonic sensor

### ISSUE THREAD

**Issue by egrolleau** [c4ev3/EV3-API#5]
Hi,

I'm trying to use a NXT ultrasonic sensor on the EV3 using C4EV3. From what I understand, this is an IIC sensor, therefore, I was not suprised for it not to work (always reading 0) as a US_DIST_CM sensor, which seems to be UART.

While going through C4EV3 source code, it seems the IIC is not fully implemented (commented 	//ioctl(g_iicFile, IIC_SET_CONN, &devCon); in ev3sensor.c). I just need to read the distance in cm from NXT ultrasonic sensor, so I'm trying to implement "by hand" the required function, but when trying to read it using readIicSensor(IN_4), seems I always get the value "66" in the address returned by the function.

Some help would be very welcome here.

Manu

**Comment by egrolleau** [comment]
Nevermind, I got it to work, I don't know why it wouldn't work last night. I just do:
int *us;		
us=readIicSensor(IN_4);
LcdTextf(1,0,0,"US=%5d\n",*us);

**Comment by a3f** [comment]
Glad you got it working :)
