### ISSUE TITLE
undefined reference to `pthread_join'

### ISSUE THREAD

**Issue by DmytroLebed** [c4ev3/EV3-API#50]
I built the latest version, and I use Eclipse Plugin.
What I did wrong?

![2020-07-08_092741](https://user-images.githubusercontent.com/57542661/86885534-1f71cf80-c0fe-11ea-9844-fe4e4cf7d768.png)

**Comment by a3f** [comment]
You need to add `-pthread` to both your compiler and linker options.

**Comment by DmytroLebed** [comment]
Thank you very much, everything worked out, I was only at the beginning of my acquaintance with C ++.
If you allow, one more question related to ev3duder, I asked it but did not receive an answer.

Windows 10, I try FW 1.09H and 1.10E, Wi-Fi works fine with EV3-G, EV3-Basic.
ev3duder --tcp  all commands work except 'up'.
Use:

ev3duder --tcp=192.168.93.214 up test.rbf ../prjs/test/test.rbf
upload was successful.

File is created but zero size and after that no command is executed until reconnecting the wi-fi on the brick.
By USB - no problem.

**Comment by a3f** [comment]
It used to work when I implemented it, might be that newer firmwares behave differently. I can't debug this, but if someone can and submits a pull request, it's most certainly welcome.
