### ISSUE TITLE
Confusion over files included in eclipse ide plugin

### ISSUE THREAD

**Issue by Eisverygoodletter** [c4ev3/EV3-API#56]
When I use the c4ev3 eclipse ide plugin, I noticed that the files "inputs" and "sensors" were not downloaded and included. This means I can't use functions like `ReadHTCompassSensor()` etc. Is this intended as functions like `ReadSensor()` should do the job? or should I download the non-included files and include them manually?

**Comment by a3f** [comment]
The plugin hasn't been updated for quite a while. You can clone the repository, build project and copy it over. I am happy to merge patches to automate the plugin building via CI, so it's always up to date.. :-)

**Comment by Eisverygoodletter** [comment]
Thanks!
