### ISSUE TITLE
Serial Communication

### ISSUE THREAD

**Issue by fugiro** [c4ev3/EV3-API#7]
Hi.

Is it possible to use this lib to communicate the EV3 Brick with an external board (like arduino) via usart or i2c? Thanks

**Comment by a3f** [comment]
Hello,

ev3sensor.c uses UART as well as I²C for communicating with EV3 and NXT sensors respectively. [Check it out].

Maybe you are able to adapt this to your use case.

[Check it out]: https://github.com/c4ev3/EV3-API/blob/master/API/ev3sensor.c
