### ISSUE TITLE
Too clever code

### ISSUE THREAD

**Issue by JakubVanek** [c4ev3/EV3-API#9]
Hello,

I'm rewriting ev3sensors for better maintainability and I've stumbled around a problem. The code for decoding fetched measurements is very hard to understand. 
```c
		case GYRO_ANG:
		case GYRO_RATE:
			help = *(data)&0xFFFF;
			if(help & 0x8000)
			{
				help = ((help&0x7FFF) - 0x7FFF);
			}
			return help;
```
After about an hour of thinking, I've finally discovered how it works:
```c
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>

int main(int argc, char **argv) {
  if (argc != 2) {
    puts("bad argc");
    return 1;
  }
  uint16_t data = (int16_t)strtol(argv[1], NULL, 10);
  int32_t help;
  int retval;

  // ANALYSIS
  help = data; // help = 0b_XYYYYYYY_YYYYYYYY

  printf("data: %x\n", help);
  if (help & 0x8000) { // 0b_1YYYYYYY_YYYYYYYY
    // 0b_0YYYYYYY_YYYYYYYY
    int32_t masked = help & 0x7FFF;
    printf("masked: %x\n", masked);

    // 0b_0!!!!!!!_!!!!!!!!
    int32_t inverted_sub = 0x7FFF - masked;
    printf("sub: %x\n", inverted_sub);

    // 0b_1YYYYYY_YYYYYYYYY + 1
    help = -inverted_sub;
    printf("minus: %x\n", help);
  }
  retval = help;

  // BETTER VERSION
  int16_t mine = (int16_t)data;
  if (mine < 0) mine++;

  printf("f(%d) -> %d\n", (int32_t)data, retval);
//  printf("f(%lx) -> %x\n", data, retval);
  printf("g(%d) -> %d\n", (int32_t)data, mine);
}
```
It increments each negative number by one.

Why is this operation necessary? Does NXT HT Gyro have two zero points?

Why couldn't simple if branch be used? Is the performance that bad?

**Comment by JakubVanek** [comment]
Oh, I've got an idea why is this necessary...
I guess it's for protection against the corner case, when the sensor returns -32768. When I'd need to invert the gyro polarity, I'd get -(-32768)=-32768 again for 16bit integer.

**Comment by a3f** [comment]
This indeed looks like a roundabout way to increment by one. Feel free to submit a patch about this (and about the cleanup you are doing).

Masking instead of down-casting has a slight benefit though: What happens when casting to a smaller signed integer size which doesn't fit is implementation-defined behavior. GCC defines it in a sane manner though and I don't think that was the reason. `</language-lawyer-mode>`

I am not sure either whether incrementing at all is really necessary. Maybe it's just a bad attempt on sign extension. What do you think?

**Comment by a3f** [comment]
The code is still there, want to draft up a pull request? :)

**Comment by JakubVanek** [comment]
I think this could get fixed during the splitting & reintegration of #22 

https://github.com/simonedegiacomi/EV3-API/blob/7b3dd0ee42558318e4d0cb0e3de02d6653ba8f25/src/ev3_sensors/ev3_gyro.c#L47-L52

**Comment by JakubVanek** [comment]
This is now fixed
